/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MindspacesRouteRouteImport } from './routes/mindspaces/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MindspacesIdRouteRouteImport } from './routes/mindspaces/$id/route'

const MindspacesRouteRoute = MindspacesRouteRouteImport.update({
  id: '/mindspaces',
  path: '/mindspaces',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MindspacesIdRouteRoute = MindspacesIdRouteRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => MindspacesRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mindspaces': typeof MindspacesRouteRouteWithChildren
  '/mindspaces/$id': typeof MindspacesIdRouteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mindspaces': typeof MindspacesRouteRouteWithChildren
  '/mindspaces/$id': typeof MindspacesIdRouteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mindspaces': typeof MindspacesRouteRouteWithChildren
  '/mindspaces/$id': typeof MindspacesIdRouteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/mindspaces' | '/mindspaces/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/mindspaces' | '/mindspaces/$id'
  id: '__root__' | '/' | '/mindspaces' | '/mindspaces/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MindspacesRouteRoute: typeof MindspacesRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/mindspaces': {
      id: '/mindspaces'
      path: '/mindspaces'
      fullPath: '/mindspaces'
      preLoaderRoute: typeof MindspacesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mindspaces/$id': {
      id: '/mindspaces/$id'
      path: '/$id'
      fullPath: '/mindspaces/$id'
      preLoaderRoute: typeof MindspacesIdRouteRouteImport
      parentRoute: typeof MindspacesRouteRoute
    }
  }
}

interface MindspacesRouteRouteChildren {
  MindspacesIdRouteRoute: typeof MindspacesIdRouteRoute
}

const MindspacesRouteRouteChildren: MindspacesRouteRouteChildren = {
  MindspacesIdRouteRoute: MindspacesIdRouteRoute,
}

const MindspacesRouteRouteWithChildren = MindspacesRouteRoute._addFileChildren(
  MindspacesRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MindspacesRouteRoute: MindspacesRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
